[workspace]
resolver = "3"
members = ["crates/cli", "crates/engine", "crates/mcdata"]
default-members = ["crates/cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.metadata.crane]
name = "world-transmuter"
